### DISCUSSION TITLE
Error while running tests from Gitlab

### DISCUSSION THREAD

**Discussion by shivabhardwaj18** [seleniumbase/SeleniumBase#1707] [General]
Hello,
I am getting following error when trying to run seleniumbase tests from Gitlab. Is anyone aware about it or has faced anything similar:

`        File "/usr/local/bin/seleniumbase", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/seleniumbase/console_scripts/run.py", line 773, in main
    sb_install.main()
  File "/usr/local/lib/python3.9/site-packages/seleniumbase/console_scripts/sb_install.py", line 711, in main
    raise Exception("Expecting only one file in %s!" % zip_file_path)
Exception: Expecting only one file in /usr/local/lib/python3.9/site-packages/seleniumbase/drivers/chromedriver_linux64.zip!
Cleaning up file based variables
ERROR: Job failed: command terminated with exit code 1`

My yml file looks like below:

`
```
variables:
  ENVIRONMENT: "pp"
  
stages:
  - run
  
run-sanity-tests:
  image:
    name: python:3.9.6
  stage: run
  script:
    - apt -y update
    - apt -y upgrade
    - apt-get -y install xvfb
    - export DISPLAY=:0
    - Xvfb :0 -ac -screen 0 2560x1440x24 -nolisten tcp &
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome-stable_current_amd64.deb
    - pip3 install -r requirements.txt
    - seleniumbase install chromedriver latest
    - pytest -m 'sanity' --gui --maximize-window --testEnv="$ENVIRONMENT" --reuse-session --gherkin-terminal-reporter --no-header --color=yes --code-highlight=yes -vv
  tags:
    - large
  only:
    - triggers
````
Thanks in advance for any answers!
