### DISCUSSION TITLE
Can SB run tests using the selenium/standalone-chrome?

### DISCUSSION THREAD

**Discussion by drFrankWhite** [seleniumbase/SeleniumBase#2319] [Q&A] [answered]
My company has pre-existing (non-SB) tests that use the selenium/standalone-chrome service.  Can I tell SB to use it too?

from the scheduler gitlab.yml file:
```
  services:
    - name: selenium/standalone-chrome
      alias: selenium
  variables:
    CHROMEDRIVER_URL: "http://selenium:4444"
```
