### DISCUSSION TITLE
Adding screenshots as artifacts to Azure Pipeline

### DISCUSSION THREAD

**Discussion by iceman8420** [seleniumbase/SeleniumBase#2421] [Show and tell]
I found example code to attach screenshots captured during tests run in Azure Pipeline, thought I would share a working example here.

I referenced the base Azure Pipeline example in the seleniumbase.io docs.

Called within my test script:
```
self.save_screenshot('testshot1.png')
self.save_screenshot('testshot2.png')
```

Then these two tasks in the azure_pipelines.yml to collect the screenshot and attach to the release

```
  - task: CopyFiles@1
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**testshot**'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: screenshots'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: screenshots
    condition: succeededOrFailed()
``` 

Then it will show as an artifact on the pipeline:

![image](https://github.com/seleniumbase/SeleniumBase/assets/155774289/c4edc84d-bc7b-4e03-bf96-f8d7b9e42cfa)
