### ISSUE TITLE
Add YAML support for processing capabilities files when using remote Selenium Grids

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2403]
## Add YAML support for processing capabilities files when using remote Selenium Grids

Currently, there's only support for Python and JSON formats.

Resolving this will also resolve https://github.com/seleniumbase/SeleniumBase/issues/2401

For more information on capabilities files, see: [SeleniumBase/examples/capabilities/ReadMe.md](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/capabilities/ReadMe.md)

Here's an example run command that's expected to work once this new feature is added:

```bash
pytest --browser=remote --server=USERNAME:KEY@hub.browserstack.com --port=80 --cap-file=capabilities/sample_cap_file_BS.yml
```

Here's an example `.yml` file that was generated from https://www.browserstack.com/docs/automate/capabilities:

```yml
platforms:
  - browserName: safari
    osVersion: 17
    deviceName: iPhone 15 Pro Max
buildIdentifier: ${BUILD_NUMBER}
parallelsPerPlatform: 1
projectName: My Project
browserstackLocal: true
debug: true
networkLogs: true
```
