### ISSUE TITLE
REQUEST: Official Docker Hub CI/CD Github Action

### ISSUE THREAD

**Issue by ttraxxrepo** [seleniumbase/SeleniumBase#3011]
Would it be possible to set up an official docker hub repo? It would make it significantly easier to use docker as opposed to having to build from the dockerfile every time, and those wanting to customize can just use a FROM statement in their docker if we have it on the hub.

Docker builds can be automated fairly easily by just creating a GitHub action and creating a docker account with an empty seleniumbase repo, and setting up the GitHub secrets with your docker account credentials so the action can auth into it.

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: seleniumbase/seleniumbase
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: seleniumbase/seleniumbase:latest
          labels: ${{ steps.meta.outputs.labels }}
```
